name: Manual Job Trigger Pipeline

on:
  workflow_dispatch:
    inputs:
      job_to_run:
        description: 'Which job to run? (job1, job2, or job3)'
        required: true
        default: 'job1'
        type: string
      custom_input:
        description: 'A custom input message'
        required: false
        default: 'default message'
        type: string

jobs:
  job1:
    if: ${{ github.event.inputs.job_to_run == 'job1' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Job 1 step
        run: echo "Running Job 1. Custom Input: ${{ github.event.inputs.custom_input }}"

  job2:
    if: ${{ github.event.inputs.job_to_run == 'job2' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Job 2 step
        run: echo "Running Job 2. Custom Input: ${{ github.event.inputs.custom_input }}"

  job3:
    if: ${{ github.event.inputs.job_to_run == 'job3' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Job 3 step
        run: echo "Running Job 3. Custom Input: ${{ github.event.inputs.custom_input }}"
